version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongoDatabase
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: arash
      MONGO_INITDB_ROOT_PASSWORD: arash
    volumes:
      - ./data:/data/lib
    restart: unless-stopped